export const SAMPLE_ASYNC_REQUEST = '@@rr/SAMPLE_ASYNC_REQUEST'
export const SAMPLE_ASYNC_SUCCESS = '@@rr/SAMPLE_ASYNC_SUCCESS'
export const SAMPLE_ASYNC_FAILURE = '@@rr/SAMPLE_ASYNC_FAILURE'
export const SAMPLE_ACTION = '@@rr/SAMPLE_ACTION'
